# Generated by Django 5.1.15 on 2026-01-31 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={},
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='created_at',
            new_name='applied_at',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='company',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='position',
            new_name='job_title',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='applied_date',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='notes',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('interview', 'Interview'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='applied', max_length=20),
        ),
        migrations.CreateModel(
            name='ApplicationAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_applications', models.IntegerField(default=0)),
                ('applied', models.IntegerField(default=0)),
                ('interviewed', models.IntegerField(default=0)),
                ('offer', models.IntegerField(default=0)),
                ('rejected', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
